modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved, Archeon, 2022."

[[mods]]
modId="archeon"
version="1.1.31.1.8"
displayName="Archeon"
credits="Archeon (All Rights Reserved)"
displayURL="Our CurseForge page: https://www.curseforge.com/minecraft/mc-mods/archeon   Listen to the Archeon's OST by Tim Rurkowski:  https://timrurkowski.bandcamp.com/  Follow the development here: https://twitter.com/ArcheonDev    Join our Official Discord server: https://discord.gg/hhGPj8sMzT"
logoFile="logo.png"
authors="Silent Winds Team (Aethyus, Aeramisu, Aerod, Scarecrowman, Tim Rurkowski). Contributors: Paros974, Mystoxi."
description='''
Archeon is a Minecraft mod adding a brand new dimension to the game. Explore the nature, build with tons of new blocks, defeat mobs, and more.
'''

[[dependencies.archeon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




