modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved, Archeon, 2023."

[[mods]]
modId="archeon"
version="1.1.31.9.12"
displayName="Archeon"
credits="All Rights Reserved"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Silent Winds Team (Aethyus, Aeramisu, Aerod, Scarecrowman, Tim Rurkowski, Rotch Gwylt). Contributors: Paros974, Mystoxi."
description='''
The official Archeon mod by the Silent Winds Team (Aethyus, Aeramisu, Aerod, Scarecrowman and Tim Rurkowski)! Archeon is an expansive brand new dimension to Minecraft, including new biomes, blocks, items and many other and different things to craft and discover in this new adventure.  Archeon is the first part of Sullen Rifts, an expansive Lore-based sequel of mods with tons of new additions to see.  The Sullen Rifts' Universe contains 3 mods in total, the 3 continents of its planet. You're in Archeon, the first continent of this universe to discover. Every continent is a mod of the sequel; those mods are for adventure and exploration, with bosses, biomes, and more.  - To get the new updates of this mod: https://www.curseforge.com/minecraft/mc-mods/archeon - Follow us on Twitter to see the development: https://twitter.com/ArcheonDev - Join our Discord server for support, and more: https://discord.gg/reyywJwFBQ - Contribute to the project, support & more - our GitHub page: https://github.com/Silent-Winds/Archeon  Made with <3 by the Silent Winds Team
'''

[[dependencies.archeon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




